import {StyleSheet} from 'react-native';

import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
export const styles = StyleSheet.create({
  iconStyles: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalContainer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
  },
  popupContainer: {
    width: wp(100),
    backgroundColor: '#ffffff00',
    borderRadius: 8,
    // borderTopLeftRadius: 8,
    padding: wp(5),
    height: hp(55),
  },
  modalContainer2: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    zIndex: 9999,
  },
  popupContainer2: {
    width: wp(100),
    backgroundColor: '#ffffff',
    borderRadius: 8,
    // borderTopLeftRadius: 8,
    padding: wp(5),
    height: hp(45),
  },
  indicator: {
    height: 16,
    width: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#1ba2de',
    marginRight: wp(3),
  },
  tileStyle: {
    borderColor: '#1ba2de',
    borderWidth: 1,
    width: wp(26),
    height: hp(4),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: wp(4),
    marginHorizontal: wp(1),
  },
  tileStyleApply: {
    backgroundColor: '#1ba2de',

    width: wp(26),
    height: hp(4),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: wp(4),
    marginHorizontal: wp(1),
  },
  separator: {
    height: wp(3),
  },
  listContainer: {
    marginBottom: wp(3),
  },
  clearButton: {
    flex: 1,
  },
  applyButton: {
    backgroundColor: '#1ba2de',
    flex: 2,
    alignItems: 'center',
    justifyContent: 'center',
    height: hp(5),
    borderRadius: hp(2.5),
  },
  clearText: {
    color: '#1ba2de',
    fontWeight: '700',
    fontSize: wp(4),
  },
  applyText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: wp(4),
  },
  textStyle: {
    color: '#000000',
    fontWeight: '700',
    fontSize: wp(3.2),
  },
  textStyleWh: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: wp(3.2),
  },
  inputFieldContainer: {
    // borderBottomWidth: 1,
    // borderBottomColor: '#ccc',
    borderWidth: 1,
    borderRadius: 2,
    marginTop: hp(1.5),
    backgroundColor: '#fff',
    height: hp(10),
    justifyContent: 'center',
  },
  inputFieldContainer2: {
    // borderBottomWidth: 1,
    // borderBottomColor: '#ccc',
    borderRadius: 2,
    marginTop: hp(1.5),
    backgroundColor: '#fff',
    height: hp(18),
    justifyContent: 'center',
  },
  inputField: {
    flex: 1,
    paddingHorizontal: wp(2),
    color: '#000',
    fontSize: wp(3),
    textAlignVertical: 'top',
  },
  buttonHandler: {
    marginTop: hp(1.5),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioButtonLabel: {
    fontSize: wp(3.2),
    color: '#444',
    marginLeft: wp(1),
    marginRight: wp(10),
  },
  radioButton: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginLeft: wp(1.5),
    marginTop: hp(1.5),
  },
  imgData: {
    width: wp(70),
    height: wp(70),
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    overflow: 'hidden',
    borderRadius: wp(2),
  },
  imageStyle: {
    width: wp(100),
    aspectRatio: 1 / 1,
    alignSelf: 'center',
    justifyContent: 'center',
    borderRadius: wp(5),
  },
});
